apiVersion: triliovault.trilio.io/v1
kind: License
metadata:
  name: trilio-license
spec:
  key: xLENDgwKD3jafZFLi8IwFIX3+RWBWQfSGF8DXTg1DsVaxbZuh9vMlQloWtJWxn8/9QEjrXhWIffw3ZyTt4UzdAWOCk759H04eZeiPYsRCRxCbQo7hxrpv/zLkPEBE5yob3Nx0I78hUNMnYEDAV2bE9Keo3YNkoPRaCvcoaseKb4gKzC2RgtWo/otjTvfHnHfLS+7g+JYgj33yOk2jMI1W2YfahurVCUsCgMVJ4p9qpgttkp9tZZZROLmmKNb77Oq3f8AYB5J0J3QhfMuOy4skkTF9In89p6N+IQPR3tgQsoB87y9x/J86DEpOJcop3LAOYlusbt4P93Nsii9McZj/ZJxbQV65T8WtGmc/oEKX/xfoosSn0S55lw2OWa9Du7DAErQpu7W73u8FQ02WfUHJ2qOaTAsAhQMxbfkEQ2w0cQ/c6FGgJUT14MY+gIUdmNDnt3VnXFfkxX5f9ZiegTUT+E=X02f7