apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: logging-loki
  namespace: openshift-logging
spec:
  hashRing:
    type: memberlist
  limits:
    global:
      retention:
        days: 1
      ingestion:
        ingestionRate: 8
        ingestionBurstSize: 16
        maxLabelNameLength: 1024
        maxLabelValueLength: 2048
        maxLabelNamesPerSeries: 30
        maxGlobalStreamsPerTenant: 10000
        maxLineSize: 256000
      queries:
        maxEntriesLimitPerQuery: 10000
        maxChunksPerQuery: 2000000
        maxQuerySeries: 1000
        queryTimeout: 1m
  managementState: Managed
  replicationFactor: 1
  size: 1x.pico
  storage:
    schemas:
      - effectiveDate: '2025-10-07'
        version: v13
    secret:
      name: logging-loki-azure
      type: azure
  storageClassName: azurefile-csi
  tenants:
    mode: openshift-logging