apiVersion: v1
kind: Secret
metadata:
  name: thanos-object-storage
  namespace: open-cluster-management-observability
type: Opaque
stringData:
  thanos.yaml: |
    type: AZURE
    config:
      storage_account: lalalal
      storage_account_key: lalallala
      container: acm-observability
      endpoint: lalalala
      max_retries: 0