apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
metadata:
  name: master-add-cpu-mem
spec:
  machineConfigPoolSelector:
    matchLabels:
      pools.operator.machineconfiguration.openshift.io/master: ''
  kubeletConfig:
    systemReserved:
      cpu: 8000m
      memory: 16Gi
---
apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
metadata:
  name: set-max-pods-master
spec:
  machineConfigPoolSelector:
    matchLabels:
      pools.operator.machineconfiguration.openshift.io/master: ""
  kubeletConfig:
    maxPods: 600